######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 5 22:24:22 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += staticlib

# Input
HEADERS += QSerialPort.h
SOURCES += QSerialPort.cpp
